"""Generate frontend/lib/facets.ts from cookpad_recipe/facet_vocab.json.
If the vocab file is missing, emits a valid skeleton (4 facets, empty term lists)
so the frontend still typechecks; rerun after crawl_facets to fill terms.

Run from backend:
    python -m scripts.gen_facets_ts
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[2]
VOCAB = ROOT / "cookpad_recipe" / "facet_vocab.json"
OUT = ROOT / "frontend" / "lib" / "facets.ts"

# order + UI label per facet (param == key)
META = [
    ("region", "Vùng miền"),
    ("occasion", "Dịp nấu"),
    ("dish_type", "Loại món"),
    ("diet", "Chế độ ăn"),
]


def main() -> None:
    vocab = json.loads(VOCAB.read_text(encoding="utf-8")) if VOCAB.exists() else {}
    facets = []
    for key, label in META:
        terms = vocab.get(key, [])
        facets.append({"key": key, "param": key, "label": label, "terms": terms})
    body = (
        "// AUTO-GENERATED by backend/scripts/gen_facets_ts.py — do not edit by hand.\n"
        "export type FacetTerm = { value: string; label: string };\n"
        "export type Facet = { key: string; param: string; label: string; terms: FacetTerm[] };\n\n"
        "export const FACETS: Facet[] = " + json.dumps(facets, ensure_ascii=False, indent=2) + ";\n"
    )
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT} ({sum(len(f['terms']) for f in facets)} terms total)")


if __name__ == "__main__":
    main()
