// AUTO-GENERATED by backend/scripts/gen_facets_ts.py — do not edit by hand.
export type FacetTerm = { value: string; label: string };
export type Facet = { key: string; param: string; label: string; terms: FacetTerm[] };

export const FACETS: Facet[] = [
  {
    "key": "region",
    "param": "region",
    "label": "Vùng miền",
    "terms": [
      {
        "value": "mon-a",
        "label": "Mon A"
      },
      {
        "value": "mon-au",
        "label": "Mon Au"
      },
      {
        "value": "mon-ngon-mien-bac",
        "label": "Mon Ngon Mien Bac"
      },
      {
        "value": "mon-ngon-mien-nam",
        "label": "Mon Ngon Mien Nam"
      },
      {
        "value": "mon-ngon-mien-trung",
        "label": "Mon Ngon Mien Trung"
      }
    ]
  },
  {
    "key": "occasion",
    "param": "occasion",
    "label": "Dịp nấu",
    "terms": [
      {
        "value": "20-10",
        "label": "20 10"
      },
      {
        "value": "bua-sang",
        "label": "Bua Sang"
      },
      {
        "value": "bua-toi",
        "label": "Bua Toi"
      },
      {
        "value": "bua-trua",
        "label": "Bua Trua"
      },
      {
        "value": "le-hoi-hoa-trang",
        "label": "Le Hoi Hoa Trang"
      },
      {
        "value": "le-tiec-khac",
        "label": "Le Tiec Khac"
      },
      {
        "value": "mon-ngon-cuoi-tuan",
        "label": "Mon Ngon Cuoi Tuan"
      },
      {
        "value": "mon-ngon-dip-giang-sinh",
        "label": "Mon Ngon Dip Giang Sinh"
      },
      {
        "value": "mon-ngon-ngay-sinh-nhat",
        "label": "Mon Ngon Ngay Sinh Nhat"
      },
      {
        "value": "mon-ngon-ngay-tet-moi",
        "label": "Mon Ngon Ngay Tet Moi"
      },
      {
        "value": "ngay-he",
        "label": "Ngay He"
      },
      {
        "value": "thuc-don-hang-ngay",
        "label": "Thuc Don Hang Ngay"
      },
      {
        "value": "trung-thu",
        "label": "Trung Thu"
      }
    ]
  },
  {
    "key": "dish_type",
    "param": "dish_type",
    "label": "Loại món",
    "terms": [
      {
        "value": "an-vat",
        "label": "An Vat"
      },
      {
        "value": "cac-mon-an-kem-mon-phu",
        "label": "Cac Mon An Kem Mon Phu"
      },
      {
        "value": "cac-mon-chay-ngon",
        "label": "Cac Mon Chay Ngon"
      },
      {
        "value": "mon-man",
        "label": "Mon Man"
      },
      {
        "value": "mon-nhau",
        "label": "Mon Nhau"
      }
    ]
  },
  {
    "key": "diet",
    "param": "diet",
    "label": "Chế độ ăn",
    "terms": [
      {
        "value": "an-chay",
        "label": "An Chay"
      },
      {
        "value": "an-kieng",
        "label": "An Kieng"
      },
      {
        "value": "bo-mat",
        "label": "Bo Mat"
      },
      {
        "value": "bo-mau",
        "label": "Bo Mau"
      },
      {
        "value": "cam-cum",
        "label": "Cam Cum"
      },
      {
        "value": "can-bang-dinh-duong",
        "label": "Can Bang Dinh Duong"
      },
      {
        "value": "giam-khoi-mo-thua-cua-co-the",
        "label": "Giam Khoi Mo Thua Cua Co The"
      },
      {
        "value": "giam-met-moi-kiet-suc",
        "label": "Giam Met Moi Kiet Suc"
      },
      {
        "value": "giup-lam-viec-tri-nao-hieu-qua",
        "label": "Giup Lam Viec Tri Nao Hieu Qua"
      },
      {
        "value": "ho-tro-cho-gan-khoe-manh",
        "label": "Ho Tro Cho Gan Khoe Manh"
      },
      {
        "value": "ho-tro-cho-than-khoe-manh",
        "label": "Ho Tro Cho Than Khoe Manh"
      },
      {
        "value": "ho-tro-he-tieu-hoa",
        "label": "Ho Tro He Tieu Hoa"
      },
      {
        "value": "ho-tro-mien-dich",
        "label": "Ho Tro Mien Dich"
      },
      {
        "value": "ho-tro-tim-va-mach-mau",
        "label": "Ho Tro Tim Va Mach Mau"
      },
      {
        "value": "ho-tro-xay-dung-khoi-co-xuong",
        "label": "Ho Tro Xay Dung Khoi Co Xuong"
      },
      {
        "value": "hoi-phuc-sau-cam",
        "label": "Hoi Phuc Sau Cam"
      },
      {
        "value": "loang-xuong-moi",
        "label": "Loang Xuong Moi"
      },
      {
        "value": "tang-nang-luong",
        "label": "Tang Nang Luong"
      },
      {
        "value": "tot-cho-da",
        "label": "Tot Cho Da"
      },
      {
        "value": "tot-cho-xuong",
        "label": "Tot Cho Xuong"
      }
    ]
  }
];
