// AUTO-GENERATED by backend/scripts/gen_facets_ts.py — do not edit by hand.
export type FacetTerm = { value: string; label: string };
export type FacetGroup = { label?: string; terms: FacetTerm[] };
export type Facet = { key: string; param: string; label: string; groups: FacetGroup[] };

export const FACETS: Facet[] = [
  {
    "key": "main_ingredient",
    "param": "main_ingredient",
    "label": "Nguyên liệu",
    "groups": [
      {
        "terms": [
          {
            "label": "Thịt Vịt",
            "value": "thit-vit"
          },
          {
            "label": "Thịt Bò",
            "value": "mon-ngon-tu-thit-bo"
          },
          {
            "label": "Thịt Heo",
            "value": "mon-ngon-tu-thit-heo"
          },
          {
            "label": "Thịt Gà",
            "value": "mon-ngon-tu-thit-ga"
          },
          {
            "label": "Các Loại Thịt Khác",
            "value": "thit-khac"
          }
        ],
        "label": "Thịt"
      },
      {
        "terms": [
          {
            "label": "Ốc",
            "value": "mon-oc"
          },
          {
            "label": "Ếch",
            "value": "mon-ech"
          },
          {
            "label": "Cá",
            "value": "mon-ngon-tu-ca"
          },
          {
            "label": "Tôm",
            "value": "mon-ngon-tu-tom"
          },
          {
            "label": "Mực/Bạch Tuộc",
            "value": "mon-ngon-tu-muc"
          },
          {
            "label": "Hải Sản Khác",
            "value": "hai-san-khac"
          }
        ],
        "label": "Hải Sản"
      },
      {
        "terms": [
          {
            "label": "Các Loại Rau",
            "value": "cac-loai-rau"
          },
          {
            "label": "Cà Rốt",
            "value": "mon-ngon-tu-ca-rot"
          },
          {
            "label": "Củ Quả",
            "value": "cu-qua"
          },
          {
            "label": "Cà Chua",
            "value": "mon-ngon-tu-ca-chua"
          },
          {
            "label": "Nấm",
            "value": "mon-ngon-tu-nam"
          },
          {
            "label": "Rau Củ Quả Khác",
            "value": "rau-cu-qua-khac"
          }
        ],
        "label": "Rau Củ Quả"
      },
      {
        "terms": [
          {
            "label": "Phở/Bún/Hủ Tiếu/Miến",
            "value": "pho-bun-hu-tieu-mien"
          },
          {
            "label": "Gạo",
            "value": "gao"
          },
          {
            "label": "Bánh Mì",
            "value": "mon-ngon-tu-banh-mi"
          }
        ],
        "label": "Tinh Bột"
      },
      {
        "terms": [
          {
            "label": "Đậu Hũ",
            "value": "mon-ngon-tu-dau-hu"
          },
          {
            "label": "Trứng",
            "value": "mon-ngon-tu-trung"
          },
          {
            "label": "Khác",
            "value": "nguyen-lieu-khac"
          }
        ],
        "label": "Khác"
      }
    ]
  },
  {
    "key": "cooking_method",
    "param": "cooking_method",
    "label": "Cách nấu",
    "groups": [
      {
        "terms": [
          {
            "label": "Quay/Rôti",
            "value": "cac-mon-quay-ngon"
          },
          {
            "label": "Nướng",
            "value": "cac-mon-nuong-ngon"
          },
          {
            "label": "Chiên",
            "value": "cac-mon-chien-ngon"
          },
          {
            "label": "Hấp/Tiềm",
            "value": "cac-mon-hap-ngon"
          },
          {
            "label": "Gỏi/Trộn",
            "value": "cac-mon-goi-ngon"
          },
          {
            "label": "Hầm",
            "value": "cac-mon-ham-ngon"
          },
          {
            "label": "Lẩu",
            "value": "cac-mon-lau-ngon"
          },
          {
            "label": "Món Xào",
            "value": "cac-mon-xao-ngon"
          },
          {
            "label": "Canh/Súp",
            "value": "cach-mon-canh-ngon"
          },
          {
            "label": "Om/Rim",
            "value": "cac-mon-om-ngon"
          },
          {
            "label": "Kho",
            "value": "cac-mon-kho-ngon"
          },
          {
            "label": "Khác",
            "value": "cach-nau-khac"
          }
        ]
      }
    ]
  },
  {
    "key": "occasion",
    "param": "occasion",
    "label": "Dịp lễ",
    "groups": [
      {
        "terms": [
          {
            "label": "20/10",
            "value": "20-10"
          },
          {
            "label": "Trung Thu",
            "value": "trung-thu"
          },
          {
            "label": "Ngày Hè",
            "value": "ngay-he"
          },
          {
            "label": "Lễ Hội Hóa Trang",
            "value": "le-hoi-hoa-trang"
          },
          {
            "label": "Tết",
            "value": "mon-ngon-ngay-tet-moi"
          },
          {
            "label": "Giáng Sinh",
            "value": "mon-ngon-dip-giang-sinh"
          },
          {
            "label": "Sinh Nhật",
            "value": "mon-ngon-ngay-sinh-nhat"
          },
          {
            "label": "Khác",
            "value": "le-tiec-khac"
          }
        ],
        "label": "Lễ Tiệc"
      },
      {
        "terms": [
          {
            "label": "Bữa Sáng",
            "value": "bua-sang"
          },
          {
            "label": "Bữa Trưa",
            "value": "bua-trua"
          },
          {
            "label": "Bữa Tối",
            "value": "bua-toi"
          },
          {
            "label": "Cuối Tuần",
            "value": "mon-ngon-cuoi-tuan"
          },
          {
            "label": "Thực Đơn Hàng Ngày",
            "value": "thuc-don-hang-ngay"
          }
        ],
        "label": "Ngày"
      }
    ]
  },
  {
    "key": "dish_type",
    "param": "dish_type",
    "label": "Món ăn",
    "groups": [
      {
        "terms": [
          {
            "label": "Ăn Vặt",
            "value": "an-vat"
          },
          {
            "label": "Các Món Ăn Kèm/Món Phụ",
            "value": "cac-mon-an-kem-mon-phu"
          },
          {
            "label": "Món Chay",
            "value": "cac-mon-chay-ngon"
          },
          {
            "label": "Món Nhậu",
            "value": "mon-nhau"
          },
          {
            "label": "Món Mặn",
            "value": "mon-man"
          }
        ]
      }
    ]
  },
  {
    "key": "region",
    "param": "region",
    "label": "Vùng miền",
    "groups": [
      {
        "terms": [
          {
            "label": "Món Á",
            "value": "mon-a"
          },
          {
            "label": "Món Âu",
            "value": "mon-au"
          },
          {
            "label": "Bắc",
            "value": "mon-ngon-mien-bac"
          },
          {
            "label": "Trung",
            "value": "mon-ngon-mien-trung"
          },
          {
            "label": "Nam",
            "value": "mon-ngon-mien-nam"
          }
        ]
      }
    ]
  },
  {
    "key": "diet",
    "param": "diet",
    "label": "Theo nhu cầu dinh dưỡng",
    "groups": [
      {
        "terms": [
          {
            "label": "Hỗ Trợ Tim Và Mạch Máu",
            "value": "ho-tro-tim-va-mach-mau"
          },
          {
            "label": "Hỗ Trợ Hệ Tiêu Hóa",
            "value": "ho-tro-he-tieu-hoa"
          },
          {
            "label": "Hỗ Trợ Xây Dựng Khối Cơ Xương",
            "value": "ho-tro-xay-dung-khoi-co-xuong"
          },
          {
            "label": "Hỗ Trợ Cho Thận Khỏe Mạnh",
            "value": "ho-tro-cho-than-khoe-manh"
          },
          {
            "label": "Hỗ Trợ Cho Gan Khỏe Mạnh",
            "value": "ho-tro-cho-gan-khoe-manh"
          },
          {
            "label": "Giúp Làm Việc Trí Não Hiệu Quả",
            "value": "giup-lam-viec-tri-nao-hieu-qua"
          },
          {
            "label": "Giảm Khối Mỡ Thừa Của Cơ Thể",
            "value": "giam-khoi-mo-thua-cua-co-the"
          },
          {
            "label": "Bổ Máu",
            "value": "bo-mau"
          },
          {
            "label": "Cân Bằng Dinh Dưỡng",
            "value": "can-bang-dinh-duong"
          },
          {
            "label": "Bổ Mắt",
            "value": "bo-mat"
          },
          {
            "label": "Cảm Cúm",
            "value": "cam-cum"
          },
          {
            "label": "Loãng Xương",
            "value": "loang-xuong-moi"
          }
        ]
      }
    ]
  }
];
